import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  foldFolderEdges,
  folderOf,
  renderFrontendModulesDiagram,
} from "../quality/frontendModulesDiagram.mts";

const reportJson = readFileSync(
  join(__dirname, "fixtures/quality/dependencyCruiserModules.json"),
  "utf8",
);

describe("folderOf", () => {
  it("answers with the deepest architectural folder holding the module", () => {
    expect(folderOf("src/domain/ports/facilitator/lifecyclePort.ts")).toBe(
      "src/domain/ports",
    );
    expect(folderOf("src/app/chrome/ConnectionStatus.tsx")).toBe("src/app");
  });

  it("leaves everything outside src alone", () => {
    expect(folderOf("../node_modules/react/index.js")).toBeUndefined();
  });

  it("refuses a source folder the architecture does not name", () => {
    expect(() => folderOf("src/telemetry/collector.ts")).toThrow(
      "src/telemetry/collector.ts sits in no architectural folder",
    );
  });
});

describe("foldFolderEdges", () => {
  it("collapses module dependencies onto their folders", () => {
    expect(foldFolderEdges(reportJson)).toEqual([
      { from: "src/adapters", to: "src/domain" },
      { from: "src/app", to: "src/domain" },
      { from: "src/app", to: "src/domain/ports" },
      { from: "src/app/facilitator", to: "src/adapters" },
      { from: "src/app/facilitator", to: "src/app" },
      { from: "src/domain/ports", to: "src/domain" },
      { from: "src/domain/ports", to: "src/shared" },
    ]);
  });

  it("leaves the test modules out of the picture", () => {
    expect(foldFolderEdges(reportJson)).not.toContainEqual({
      from: "src/adapters",
      to: "src/adapters",
    });
    expect(
      foldFolderEdges(
        JSON.stringify({
          modules: [
            {
              source: "src/domain/__tests__/session.test.ts",
              dependencies: [{ resolved: "src/adapters/workshopSessions.ts" }],
            },
          ],
        }),
      ),
    ).toEqual([]);
  });

  it("refuses a report that is not a module graph", () => {
    expect(() => foldFolderEdges('{"summary":{}}')).toThrow();
  });
});

describe("renderFrontendModulesDiagram", () => {
  const diagram = renderFrontendModulesDiagram(reportJson);

  it("titles itself and announces that it is generated", () => {
    expect(diagram.split("\n").slice(0, 5)).toEqual([
      "---",
      'title: "frontend/src — folder dependencies, as dependency-cruiser sees them"',
      "---",
      "%% Generated by `pnpm quality:report`. Edit the generator, never this file.",
      "graph LR",
    ]);
  });

  it("nests the screen groups and the ports in their own areas", () => {
    expect(diagram).toContain('subgraph srcAppArea["app/"]');
    expect(diagram).toContain('srcAppFacilitator["app/facilitator"]');
    expect(diagram).toContain('subgraph srcDomainArea["domain/"]');
    expect(diagram).toContain('srcDomainPorts["domain/ports"]');
  });

  it("draws one arrow per folder dependency", () => {
    expect(diagram).toContain("srcAppFacilitator --> srcAdapters");
    expect(diagram).toContain("srcDomainPorts --> srcShared");
    expect(diagram).not.toContain("srcDomain --> src");
  });
});
