import type {
  Hotspot,
  HotspotMetrics,
} from "../quality/hotspots/hotspotAnalysis.mts";
import {
  hotspotsDiagramPath,
  plottedHotspots,
  renderHotspotsDiagram,
} from "../quality/hotspots/hotspotsDiagram.mts";
import { RepositorySide } from "../quality/sizeScan.mts";
import { sampleQualityReport } from "../testing/sampleQualityReport.mts";

function hotspot(path: string, commits: number, complexity: number): Hotspot {
  return {
    path,
    side: path.startsWith("backend/")
      ? RepositorySide.Backend
      : RepositorySide.Frontend,
    commits,
    linesChanged: commits * 10,
    complexity,
    maximumDepth: 3,
    score: commits * complexity,
  };
}

function metricsOf(hotspots: Hotspot[]): HotspotMetrics {
  return {
    filesAnalysed: 500,
    commitsInHistory: 800,
    hotspots,
    maxima: {
      commits: Math.max(...hotspots.map((entry) => entry.commits)),
      complexity: Math.max(...hotspots.map((entry) => entry.complexity)),
    },
  };
}

describe("renderHotspotsDiagram", () => {
  it("draws the top hotspots on a quadrant chart scaled to the busiest and the most complex file, clear of the borders", () => {
    expect(renderHotspotsDiagram(sampleQualityReport.hotspots)).toBe(
      [
        "---",
        'title: "Hotspots — where change and complexity meet"',
        "config:",
        "  quadrantChart:",
        "    chartWidth: 800",
        "    chartHeight: 560",
        "---",
        "%% Generated by `pnpm quality:report`. Edit the generator, never this file.",
        "quadrantChart",
        "    x-axis Rarely changed --> Changed often",
        "    y-axis Simple --> Complex",
        "    quadrant-1 Hotspots — refactor first",
        "    quadrant-2 Complex, quiet",
        "    quadrant-3 Quiet, simple",
        "    quadrant-4 Volatile, simple",
        '    "Session.cs": [0.9, 0.79]',
        '    "facilitator/page.tsx": [0.55, 0.45]',
        '    "participant/page.tsx": [0.49, 0.42]',
        "",
      ].join("\n"),
    );
  });

  it("keeps every point inside the chart with room for its label, the extremes included", () => {
    const diagram = renderHotspotsDiagram(
      metricsOf([
        hotspot("backend/Domain/Session.cs", 3, 7),
        hotspot("frontend/src/domain/session.ts", 1, 1),
        hotspot("frontend/src/domain/quiet.ts", 0, 0),
      ]),
    );
    expect(diagram).toContain('"Session.cs": [0.9, 0.9]');
    expect(diagram).toContain('"session.ts": [0.37, 0.21]');
    expect(diagram).toContain('"quiet.ts": [0.1, 0.1]');
  });

  it("names a point by its file, and by as much of its folder as it takes to tell twins apart", () => {
    const diagram = renderHotspotsDiagram(
      metricsOf([
        hotspot("frontend/src/app/facilitator/page.tsx", 5, 5),
        hotspot("frontend/src/app/participant/page.tsx", 4, 4),
        hotspot("backend/Domain/Session.cs", 3, 3),
        hotspot("backend/Application/Session.cs", 2, 2),
        hotspot("frontend/src/domain/session.ts", 1, 1),
      ]),
    );
    expect(diagram).toContain('"facilitator/page.tsx": [0.9, 0.9]');
    expect(diagram).toContain('"participant/page.tsx": [0.74, 0.74]');
    expect(diagram).toContain('"Domain/Session.cs": [0.58, 0.58]');
    expect(diagram).toContain('"Application/Session.cs": [0.42, 0.42]');
    expect(diagram).toContain('"session.ts": [0.26, 0.26]');
  });

  it("plots the top twelve and leaves the rest to the table", () => {
    const many = Array.from({ length: 15 }, (_, index) =>
      hotspot(`backend/Domain/File${index}.cs`, 15 - index, 10),
    );
    const points = renderHotspotsDiagram(metricsOf(many))
      .split("\n")
      .filter((line) => line.includes(": ["));
    expect(plottedHotspots).toBe(12);
    expect(points).toHaveLength(12);
    expect(points[0]).toBe('    "File0.cs": [0.9, 0.9]');
    expect(points[11]).toBe('    "File11.cs": [0.31, 0.9]');
  });

  it("puts a file nobody changed in the corner rather than dividing by zero", () => {
    const diagram = renderHotspotsDiagram({
      filesAnalysed: 1,
      commitsInHistory: 1,
      hotspots: [hotspot("backend/Domain/Flat.cs", 0, 0)],
      maxima: { commits: 0, complexity: 0 },
    });
    expect(diagram).toContain('"Flat.cs": [0.1, 0.1]');
  });

  it("is written next to the other generated diagrams", () => {
    expect(hotspotsDiagramPath).toBe("docs/quality/hotspots.mmd");
  });
});
