import { identifierOf, mermaidDocument } from "../quality/mermaidDocument.mts";

describe("mermaidDocument", () => {
  it("opens with the title and the generated-file notice", () => {
    expect(mermaidDocument("A title", ["graph LR", "    a --> b"])).toBe(
      [
        "---",
        'title: "A title"',
        "---",
        "%% Generated by `pnpm quality:report`. Edit the generator, never this file.",
        "graph LR",
        "    a --> b",
        "",
      ].join("\n"),
    );
  });
});

describe("identifierOf", () => {
  it("turns a path into a camel-cased mermaid node id", () => {
    expect(identifierOf("src/app/facilitator")).toBe("srcAppFacilitator");
    expect(identifierOf(".github")).toBe("github");
  });

  it("refuses a path without a usable character", () => {
    expect(() => identifierOf("/-/")).toThrow(
      '"/-/" holds no character a mermaid node id can use.',
    );
  });
});
