import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  renderRepoStructureDiagram,
  trackedTopLevelDirectories,
} from "../quality/repoStructureDiagram.mts";

const trackedPaths = readFileSync(
  join(__dirname, "fixtures/quality/gitLsFilesTopLevel.txt"),
  "utf8",
)
  .split("\n")
  .filter((line) => line.length > 0);

describe("trackedTopLevelDirectories", () => {
  it("keeps the directories git tracks and drops the files beside them", () => {
    expect(trackedTopLevelDirectories(trackedPaths)).toEqual([
      ".github",
      ".pi",
      "backend",
      "config",
      "contract",
      "design",
      "devtools",
      "docs",
      "e2e",
      "frontend",
      "patches",
      "scripts",
      "tasks",
    ]);
  });
});

describe("renderRepoStructureDiagram", () => {
  const diagram = renderRepoStructureDiagram(trackedPaths);

  it("announces itself as generated and opens a mermaid graph", () => {
    expect(diagram.split("\n").slice(0, 5)).toEqual([
      "---",
      'title: "The repository, top level — what each directory holds and what checks it"',
      "---",
      "%% Generated by `pnpm quality:report`. Edit the generator, never this file.",
      "graph TD",
    ]);
  });

  it("groups every tracked directory by what it is", () => {
    expect(diagram).toContain('subgraph productCode["product code"]');
    expect(diagram).toContain(
      'frontend["frontend/<br/>Next.js app — the facilitator, participant and presenter screens"]',
    );
    expect(diagram).toContain('subgraph documentation["documentation"]');
    expect(diagram).toContain(
      'tasks["tasks/<br/>The plan, the backlog and the per-task mini-specs"]',
    );
  });

  it("marks the directories a build gate reads apart from the prose", () => {
    expect(diagram).toContain(
      "class frontend,backend,config,contract,e2e,scripts,devtools,patches,github,legendChecked checked;",
    );
    expect(diagram).toContain(
      "class pi,design,docs,tasks,legendUnchecked unchecked;",
    );
  });

  it("refuses to leave a newly tracked directory off the map", () => {
    expect(() =>
      renderRepoStructureDiagram([...trackedPaths, "telemetry/collector.ts"]),
    ).toThrow(
      "git tracks telemetry, which the repository map does not describe.",
    );
  });

  it("refuses to keep a directory git no longer tracks", () => {
    expect(() =>
      renderRepoStructureDiagram(
        trackedPaths.filter((path) => !path.startsWith("patches/")),
      ),
    ).toThrow(
      "The repository map describes patches, which git no longer tracks.",
    );
  });
});
