export const generatedDiagramNotice =
  "%% Generated by `pnpm quality:report`. Edit the generator, never this file.";

export type DiagramConfiguration = Readonly<
  Record<string, Readonly<Record<string, number>>>
>;

function configurationLines(configuration: DiagramConfiguration): string[] {
  const diagrams = Object.entries(configuration);
  if (diagrams.length === 0) {
    return [];
  }
  return [
    "config:",
    ...diagrams.flatMap(([diagram, settings]) => [
      `  ${diagram}:`,
      ...Object.entries(settings).map(
        ([setting, value]) => `    ${setting}: ${value}`,
      ),
    ]),
  ];
}

export function mermaidDocument(
  title: string,
  lines: readonly string[],
  configuration: DiagramConfiguration = {},
): string {
  const document = [
    "---",
    `title: "${title}"`,
    ...configurationLines(configuration),
    "---",
    generatedDiagramNotice,
    ...lines,
  ];
  return `${document.join("\n")}\n`;
}

export function identifierOf(path: string): string {
  const words = path.split(/[^A-Za-z0-9]+/).filter((word) => word.length > 0);
  if (words.length === 0) {
    throw new Error(`"${path}" holds no character a mermaid node id can use.`);
  }
  return words
    .map((word, index) =>
      index === 0
        ? `${word[0].toLowerCase()}${word.slice(1)}`
        : `${word[0].toUpperCase()}${word.slice(1)}`,
    )
    .join("");
}

export function indented(lines: readonly string[]): string[] {
  return lines.map((line) => (line === "" ? line : `    ${line}`));
}

export function node(identifier: string, label: string): string {
  return `${identifier}["${label}"]`;
}

export function subgraph(
  identifier: string,
  label: string,
  body: readonly string[],
): string[] {
  return [`subgraph ${identifier}["${label}"]`, ...indented(body), "end"];
}
