using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ValuesWorkshop.Adapters.Persistence;

internal static class DatabaseDiagram
{
    private const string Title = "The workshop database — the schema EF Core maps onto SQLite";
    private const string GeneratedNotice =
        "%% Generated by `pnpm quality:report`. Edit the generator, never this file.";

    internal static string Render(IModel model)
    {
        var entityTypes = model
            .GetEntityTypes()
            .OrderBy(TableNameOf, StringComparer.Ordinal)
            .ToList();

        string[] lines =
        [
            "---",
            $"title: \"{Title}\"",
            "---",
            GeneratedNotice,
            "erDiagram",
            .. entityTypes.SelectMany(TableBlock),
            .. entityTypes
                .SelectMany(entityType => entityType.GetForeignKeys())
                .Select(RelationshipLine)
                .Order(StringComparer.Ordinal),
        ];

        return string.Join("\n", lines) + "\n";
    }

    private static IEnumerable<string> TableBlock(IEntityType entityType)
    {
        return
        [
            $"    {TableNameOf(entityType)} {{",
            .. ColumnOrder(entityType)
                .Select(property => $"        {ColumnLine(entityType, property)}"),
            "    }",
        ];
    }

    private static IEnumerable<IProperty> ColumnOrder(IEntityType entityType)
    {
        var primaryKey = PrimaryKeyOf(entityType).Properties;

        return
        [
            .. primaryKey,
            .. entityType
                .GetProperties()
                .Except(primaryKey)
                .OrderBy(ColumnNameOf, StringComparer.Ordinal),
        ];
    }

    private static string ColumnLine(IEntityType entityType, IProperty property)
    {
        string[] parts =
        [
            property.GetColumnType(),
            ColumnNameOf(property),
            KeyMarkersOf(entityType, property),
            property.IsNullable ? "\"nullable\"" : "",
        ];

        return string.Join(' ', parts.Where(part => part.Length > 0));
    }

    private static string KeyMarkersOf(IEntityType entityType, IProperty property)
    {
        string[] markers =
        [
            PrimaryKeyOf(entityType).Properties.Contains(property) ? "PK" : "",
            entityType.GetForeignKeys().Any(key => key.Properties.Contains(property)) ? "FK" : "",
            IsPartOfUniqueKey(entityType, property) ? "UK" : "",
        ];

        return string.Join(", ", markers.Where(marker => marker.Length > 0));
    }

    private static bool IsPartOfUniqueKey(IEntityType entityType, IProperty property)
    {
        var alternateKeys = entityType
            .GetKeys()
            .Where(key => !key.IsPrimaryKey())
            .Select(key => key.Properties);
        var uniqueIndexes = entityType
            .GetIndexes()
            .Where(index => index.IsUnique)
            .Select(index => index.Properties);

        return alternateKeys.Concat(uniqueIndexes).Any(properties => properties.Contains(property));
    }

    private static string RelationshipLine(IForeignKey foreignKey)
    {
        var columns = string.Join(", ", foreignKey.Properties.Select(ColumnNameOf));

        return $"    {TableNameOf(foreignKey.PrincipalEntityType)} "
            + $"{CardinalityOf(foreignKey)} "
            + $"{TableNameOf(foreignKey.DeclaringEntityType)} : \"{columns}\"";
    }

    private static string CardinalityOf(IForeignKey foreignKey)
    {
        var principalSide = foreignKey.IsRequired ? "||" : "|o";
        var dependentSide = foreignKey.IsUnique ? "o|" : "o{";

        return $"{principalSide}--{dependentSide}";
    }

    private static IKey PrimaryKeyOf(IEntityType entityType)
    {
        return entityType.FindPrimaryKey()
            ?? throw new InvalidOperationException(
                $"{entityType.DisplayName()} has no primary key, which no table in this schema may lack."
            );
    }

    private static string TableNameOf(IReadOnlyEntityType entityType)
    {
        return entityType.GetTableName()
            ?? throw new InvalidOperationException(
                $"{entityType.DisplayName()} maps to no table, so it cannot be drawn."
            );
    }

    private static string ColumnNameOf(IReadOnlyProperty property)
    {
        return property.GetColumnName()
            ?? throw new InvalidOperationException(
                $"{property.DeclaringType.DisplayName()}.{property.Name} maps to no column, so it cannot be drawn."
            );
    }
}
