// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ValuesWorkshop.Adapters.Persistence;

#nullable disable

namespace ValuesWorkshop.Adapters.Persistence.Migrations
{
    [DbContext(typeof(WorkshopDbContext))]
    partial class WorkshopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.GroupActionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("group_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<string>("ValueId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value_id");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("group_actions", (string)null);
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.GroupAssignedValueEntity", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("group_id");

                    b.Property<string>("ValueId")
                        .HasColumnType("TEXT")
                        .HasColumnName("value_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("GroupId", "ValueId");

                    b.ToTable("group_assigned_values", (string)null);
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.GroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("IsSubmitted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_submitted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ScribeParticipantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("scribe_participant_id");

                    b.Property<string>("SessionIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("session_identity");

                    b.HasKey("Id");

                    b.HasIndex("SessionIdentity");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.GroupMemberEntity", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("group_id");

                    b.Property<string>("ParticipantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("participant_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("GroupId", "ParticipantId");

                    b.ToTable("group_members", (string)null);
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.ParticipantEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<int>("JoinOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("join_order");

                    b.Property<string>("SessionIdentity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("session_identity");

                    b.HasKey("Id");

                    b.HasIndex("SessionIdentity");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.PresentationStateEntity", b =>
                {
                    b.Property<string>("SessionIdentity")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_identity");

                    b.Property<string>("PresentedValueId")
                        .HasColumnType("TEXT")
                        .HasColumnName("presented_value_id");

                    b.Property<string>("PresentingGroupName")
                        .HasColumnType("TEXT")
                        .HasColumnName("presenting_group_name");

                    b.Property<int>("ShownValueCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shown_value_count");

                    b.HasKey("SessionIdentity");

                    b.ToTable("presentation_state", (string)null);
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.QuizAnswerEntity", b =>
                {
                    b.Property<string>("SessionIdentity")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_identity");

                    b.Property<int>("QuestionIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("question_index");

                    b.Property<string>("ParticipantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("participant_id");

                    b.Property<int>("AnswerIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("answer_index");

                    b.HasKey("SessionIdentity", "QuestionIndex", "ParticipantId");

                    b.ToTable("quiz_answers", (string)null);
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.QuizStateEntity", b =>
                {
                    b.Property<string>("SessionIdentity")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_identity");

                    b.Property<int?>("CurrentQuestionIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_question_index");

                    b.Property<bool>("IsLearningTextShown")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_learning_text_shown");

                    b.Property<bool>("IsRevealed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_revealed");

                    b.HasKey("SessionIdentity");

                    b.ToTable("quiz_state", (string)null);
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.SessionEntity", b =>
                {
                    b.Property<string>("Identity")
                        .HasColumnType("TEXT")
                        .HasColumnName("identity");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentPhase")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_phase");

                    b.Property<string>("FacilitatorSubject")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("facilitator_subject");

                    b.Property<bool>("IsFormed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_formed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER")
                        .HasColumnName("revision");

                    b.HasKey("Identity");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.TopValueEntity", b =>
                {
                    b.Property<string>("SessionIdentity")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_identity");

                    b.Property<string>("ValueId")
                        .HasColumnType("TEXT")
                        .HasColumnName("value_id");

                    b.HasKey("SessionIdentity", "ValueId");

                    b.ToTable("top_values", (string)null);
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.ValueSelectionEntity", b =>
                {
                    b.Property<string>("SessionIdentity")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_identity");

                    b.Property<string>("ParticipantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("participant_id");

                    b.Property<string>("ValueId")
                        .HasColumnType("TEXT")
                        .HasColumnName("value_id");

                    b.HasKey("SessionIdentity", "ParticipantId", "ValueId");

                    b.ToTable("value_selections", (string)null);
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.VoteTallyEntity", b =>
                {
                    b.Property<string>("SessionIdentity")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_identity");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("round_number");

                    b.Property<string>("ValueId")
                        .HasColumnType("TEXT")
                        .HasColumnName("value_id");

                    b.Property<int>("VoteCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("vote_count");

                    b.HasKey("SessionIdentity", "RoundNumber", "ValueId");

                    b.ToTable("vote_tallies", (string)null);
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.VotedParticipantEntity", b =>
                {
                    b.Property<string>("SessionIdentity")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_identity");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("round_number");

                    b.Property<string>("ParticipantId")
                        .HasColumnType("TEXT")
                        .HasColumnName("participant_id");

                    b.HasKey("SessionIdentity", "RoundNumber", "ParticipantId");

                    b.ToTable("voted_participants", (string)null);
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.VotingStateEntity", b =>
                {
                    b.Property<string>("SessionIdentity")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_identity");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("round_number");

                    b.Property<bool>("RoundOpen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("round_open");

                    b.HasKey("SessionIdentity");

                    b.ToTable("voting_state", (string)null);
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.WinningValueEntity", b =>
                {
                    b.Property<string>("SessionIdentity")
                        .HasColumnType("TEXT")
                        .HasColumnName("session_identity");

                    b.Property<string>("ValueId")
                        .HasColumnType("TEXT")
                        .HasColumnName("value_id");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rank");

                    b.HasKey("SessionIdentity", "ValueId");

                    b.ToTable("winning_values", (string)null);
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.GroupActionEntity", b =>
                {
                    b.HasOne("ValuesWorkshop.Adapters.Persistence.Entities.GroupEntity", "Group")
                        .WithMany("Actions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.GroupAssignedValueEntity", b =>
                {
                    b.HasOne("ValuesWorkshop.Adapters.Persistence.Entities.GroupEntity", "Group")
                        .WithMany("AssignedValues")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.GroupEntity", b =>
                {
                    b.HasOne("ValuesWorkshop.Adapters.Persistence.Entities.SessionEntity", "Session")
                        .WithMany("Groups")
                        .HasForeignKey("SessionIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.GroupMemberEntity", b =>
                {
                    b.HasOne("ValuesWorkshop.Adapters.Persistence.Entities.GroupEntity", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.ParticipantEntity", b =>
                {
                    b.HasOne("ValuesWorkshop.Adapters.Persistence.Entities.SessionEntity", "Session")
                        .WithMany("Participants")
                        .HasForeignKey("SessionIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.PresentationStateEntity", b =>
                {
                    b.HasOne("ValuesWorkshop.Adapters.Persistence.Entities.SessionEntity", "Session")
                        .WithOne("PresentationState")
                        .HasForeignKey("ValuesWorkshop.Adapters.Persistence.Entities.PresentationStateEntity", "SessionIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.QuizAnswerEntity", b =>
                {
                    b.HasOne("ValuesWorkshop.Adapters.Persistence.Entities.SessionEntity", "Session")
                        .WithMany("QuizAnswers")
                        .HasForeignKey("SessionIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.QuizStateEntity", b =>
                {
                    b.HasOne("ValuesWorkshop.Adapters.Persistence.Entities.SessionEntity", "Session")
                        .WithOne("QuizState")
                        .HasForeignKey("ValuesWorkshop.Adapters.Persistence.Entities.QuizStateEntity", "SessionIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.TopValueEntity", b =>
                {
                    b.HasOne("ValuesWorkshop.Adapters.Persistence.Entities.SessionEntity", "Session")
                        .WithMany("TopValues")
                        .HasForeignKey("SessionIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.ValueSelectionEntity", b =>
                {
                    b.HasOne("ValuesWorkshop.Adapters.Persistence.Entities.SessionEntity", "Session")
                        .WithMany("ValueSelections")
                        .HasForeignKey("SessionIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.VoteTallyEntity", b =>
                {
                    b.HasOne("ValuesWorkshop.Adapters.Persistence.Entities.SessionEntity", "Session")
                        .WithMany("VoteTallies")
                        .HasForeignKey("SessionIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.VotedParticipantEntity", b =>
                {
                    b.HasOne("ValuesWorkshop.Adapters.Persistence.Entities.SessionEntity", "Session")
                        .WithMany("VotedParticipants")
                        .HasForeignKey("SessionIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.VotingStateEntity", b =>
                {
                    b.HasOne("ValuesWorkshop.Adapters.Persistence.Entities.SessionEntity", "Session")
                        .WithOne("VotingState")
                        .HasForeignKey("ValuesWorkshop.Adapters.Persistence.Entities.VotingStateEntity", "SessionIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.WinningValueEntity", b =>
                {
                    b.HasOne("ValuesWorkshop.Adapters.Persistence.Entities.SessionEntity", "Session")
                        .WithMany("WinningValues")
                        .HasForeignKey("SessionIdentity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.GroupEntity", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("AssignedValues");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("ValuesWorkshop.Adapters.Persistence.Entities.SessionEntity", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Participants");

                    b.Navigation("PresentationState")
                        .IsRequired();

                    b.Navigation("QuizAnswers");

                    b.Navigation("QuizState")
                        .IsRequired();

                    b.Navigation("TopValues");

                    b.Navigation("ValueSelections");

                    b.Navigation("VoteTallies");

                    b.Navigation("VotedParticipants");

                    b.Navigation("VotingState")
                        .IsRequired();

                    b.Navigation("WinningValues");
                });
#pragma warning restore 612, 618
        }
    }
}
