<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\ValuesWorkshop.Application.csproj" />
    <ProjectReference Include="..\Domain\ValuesWorkshop.Domain.csproj" />
  </ItemGroup>
</Project>
